apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: {{ include "kuadrant.name" . }}
spec:
  limitador:
    storage:
      redis:
        configSecretRef:
          name: {{ include "kuadrant.name" . }}-redis-config
