apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kuadrant.name" . }}-job-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.observability.clusterRole }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}