---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kuadrant.name" . }}-limitador
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: limitador
