apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "kuadrant-operator.name" . }}
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: {{ .Values.subscription.name }}
  source: {{ include "kuadrant-operator.name" . }}-catalog
  sourceNamespace: {{ .Release.Namespace }}
  startingCSV: {{ .Values.subscription.startingCSV }}
 