apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ include "monitoring.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "monitoring.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "monitoring.name" . }}
  namespace: {{ .Release.Namespace }}