---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ include "monitoring.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: kube-state-metrics
      labels:
        {{- include "monitoring.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: custom-resource-state
          configMap:
            defaultMode: 420
            name: custom-resource-state
      automountServiceAccountToken: true
      containers:
        - volumeMounts:
            - name: custom-resource-state
              mountPath: /custom-resource-state
          args:
            - --port=8081
            - --telemetry-port=8082
            - --custom-resource-state-config-file
            - /custom-resource-state/custom-resource-state.yaml
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: kube-state-metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: 8081
              name: https-main
            - containerPort: 8082
              name: https-self
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ include "monitoring.name" . }}
