---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ include "monitoring.name" . }}
spec:
  clusterIP: None
  ports:
    - name: https-main
      port: 8081
      targetPort: https-main
    - name: https-self
      port: 8082
      targetPort: https-self
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}