---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ include "monitoring.name" . }}
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      port: https-main
      relabelings:
      - action: labeldrop
        regex: (pod|service|endpoint|namespace)
      scheme: http
      scrapeTimeout: 30s
    - interval: 30s
      port: https-self
      scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}