apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-proxy
  namespace: monitoring
  labels:
    app: prometheus-proxy
subsets:
  - addresses:
      - ip: 23.21.68.84
    ports:
      - name: metrics
        port: 9091
        protocol: TCP