kind: Service
apiVersion: v1
metadata:
  name: {{ include "prometheus-proxy.name" . }}
  labels:
    app: {{ include "prometheus-proxy.name" . }}
spec:
  type: ExternalName
  externalName: prometheus-k8s.openshift-monitoring.svc.cluster.local
  ports:
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
