apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-proxy.name" . }}
  labels:
    app: {{ include "prometheus-proxy.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "prometheus-proxy.name" . }}
  endpoints:
    - path: /federate
      scheme: https
      port: metrics
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __address__
          regex: (.*)
          replacement: "prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
          action: replace
      params:
        'match[]':
          - '{__name__=~"container_memory_working_set_bytes|container_network_receive_bytes_total|namespace_workload_pod:kube_pod_owner:relabel|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate"}'
      bearerTokenSecret:
        key: token
        name: prometheus-proxy
      tlsConfig:
        insecureSkipVerify: true