ingestor:
  replicaCount: 1
  image:
    repository: quay.io/thanos/thanos
    pullPolicy: IfNotPresent
    tag: "v0.29.0"
  livenessProbe:
    failureThreshold: 8
    httpGet:
      path: /-/healthy
      port: 10902
      scheme: HTTP
    periodSeconds: 30
  readinessProbe:
    failureThreshold: 20
    httpGet:
      path: /-/ready
      port: 10902
      scheme: HTTP     
    periodSeconds: 5
  resources: {}

router:
  replicaCount: 1
  image:
    repository: quay.io/thanos/thanos
    pullPolicy: IfNotPresent
    tag: "v0.29.0"
  livenessProbe:
    failureThreshold: 8
    httpGet:
      path: /-/healthy
      port: 10902
      scheme: HTTP
      httpHeaders:
        - name: Authorization
          value: Basic YWxpY2U6YWxpY2VwYXNzd29yZDFkZW1v
    periodSeconds: 30
  readinessProbe:
    failureThreshold: 20
    httpGet:
      path: /-/ready
      port: 10902
      scheme: HTTP
      httpHeaders:
        - name: Authorization
          value: Basic YWxpY2U6YWxpY2VwYXNzd29yZDFkZW1v
  resources: {}
  route:
    enabled: true
    host:
    tlsEnabled: true
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

auth:
  config:
    tls_server_config: {}
    basic_auth_users:
      alice: $2a$09$zMhj8dLod4TpmfTTMVDsKe.v7f8m/pumxFxvGeWIlUQfItme8QC7W  
