apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-role
rules:
  - apiGroups:
      - ""
      - "operator.authorino.kuadrant.io"
      - "route.openshift.io"
    resources:
      - "routes"
      - "configmaps"
      - "services"
      - "authorinos"
    verbs:
      - "*"