apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "metrics-job.name" . }}-configure-remote-write
  namespace: openshift-user-workload-monitoring
  annotations:
    {{- include "metrics-job.argocd-syncwave" . | nindent 4 }}
spec:
  template:
    spec:
      containers: 
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["patch.sh"]
          name: "configure"
      restartPolicy: OnFailure 
  backoffLimit: 15   