kind: Service
apiVersion: v1
metadata:
  name: prometheus-proxy
  namespace: monitoring
  labels:
    app: prometheus-proxy
spec:
  type: ExternalName
  externalName: prometheus-k8s.openshift-monitoring.svc.cluster.local
  ports:
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-proxy-monitor
  labels:
    app: prometheus-proxy
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-proxy
  endpoints:
  - path: /federate
    scheme: https
    port: metrics
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: __address__
        regex: (.*)
        replacement: "prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
        action: replace
    params:
      'match[]':
        - '{__name__=~"container_memory_working_set_bytes|container_network_receive_bytes_total|namespace_workload_pod:kube_pod_owner:relabel|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate"}'
    bearerTokenSecret:
      key: token
      name: prometheus-proxy
    tlsConfig:
      insecureSkipVerify: true
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-proxy
  namespace: monitoring
  labels:
    app: prometheus-proxy
subsets:
- addresses:
  - ip: 23.21.68.84
  ports:
  - name: metrics
    port: 9091
    protocol: TCP