replicaCount: 1

image:
  repository: grafana/grafana
  pullPolicy: IfNotPresent
  tag: "8.5.5"

readinessProbe:
  httpGet:
    path: /api/health
    port: http

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

thanos:
  query:
    name: thanos-query