apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ include "grafana.name" . }}
spec:
  {{- if .Values.route.tlsEnabled }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{ end }}
  to:
    kind: Service
    name: {{ include "grafana.name" . }}
    weight: 100
  wildcardPolicy: None