apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ include "grafana.name" . }}
spec:
  endpoints:
    - interval: 15s
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}