apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ include "grafana.name" . }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}