apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ include "grafana.name" . }}-datasources
stringData:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": false,
                "name": "Kuadrant-Thanos-Hub",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://{{ .Values.thanos.query.name }}.{{ .Release.Namespace }}.svc:9090",
                "version": 1,
                "jsonData": {
                    "httpMethod": "POST",
                    "manageAlerts": false,
                    "tlsSkipVerify": false
                },
                
            }
        ]
    }
type: Opaque