apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ include "grafana.name" . }}-config
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC
type: Opaque