nameOverride: kube-state-metrics-kuadrant

replicaCount: 1

image:
  repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
  pullPolicy: IfNotPresent
  tag: "v2.9.2"

resources:
  limits:
    cpu: 100m
    memory: 250Mi
  requests:
    cpu: 10m
    memory: 190Mi

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL