apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "thanos-query.labels" . | nindent 4 }}
  name: {{ include "thanos-query.name" . }}
spec:
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    {{- include "thanos-query.selectorLabels" . | nindent 4 }}
