apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "thanos-query.labels" . | nindent 4 }}
  name: {{ include "thanos-query.name" . }}
spec:
  endpoints:
    - port: http
      relabelings:
      - action: replace
        separator: /
        sourceLabels:
        - namespace
        - pod
        targetLabel: instance
  selector:
    matchLabels:
      {{- include "thanos-query.selectorLabels" . | nindent 6 }}
