apiVersion: route.openshift.io/v1
kind: Route 
metadata:
  labels:
    {{- include "thanos-query.labels" . | nindent 4 }}
  name: {{ include "thanos-query.name" . }}
spec:  
  host:
  {{- if .Values.route.tlsEnabled }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{ end }}
  to:
    kind: Service
    name: {{ include "thanos-query.name" . }}
    weight: 100
  wildcardPolicy: None