apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  name: {{ include "echo-api.name" . }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ include "echo-api.name" . }}
    namespace: {{ .Release.Namespace }}
  limits:
    "echo-api":
      rates:
      - limit: 5
        duration: 10
        unit: second
      routeSelectors:
      - matches:
        - method: GET
          path:
            type: PathPrefix
            value: "/"