apiVersion: v2
name: observability
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: thanos-query
    version: 0.1.0
    repository: file://thanos-query
  - name: thanos-receive
    version: 0.1.0
    repository: file://thanos-receive
  - name: monitoring
    version: 0.1.0
    repository: file://monitoring
  - name: metrics-job
    version: 0.1.0
    repository: file://metrics-job
