apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "thanos-receive.ingestor.labels" . | nindent 4 }}
  name: {{ include "thanos-receive.name" . }}-ingestor
spec:
  endpoints:
    - port: http
      relabelings:
        - action: replace
          separator: /
          sourceLabels:
            - namespace
            - pod
          targetLabel: instance
        - action: replace
          sourceLabels:
            - __meta_kubernetes_service_label_controller_receive_thanos_io_shard
          targetLabel: hashring
  selector:
    matchLabels:
      app.kubernetes.io/component: database-write-hashring
      app.kubernetes.io/name: {{ include "thanos-receive.name" . }}
