apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "thanos-receive.ingestor.labels" . | nindent 4 }}
  name: {{ include "thanos-receive.name" . }}-ingestor-default
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
    - name: http
      port: 10902
      targetPort: 10902
    - name: remote-write
      port: 19291
      targetPort: 19291
  selector:
    {{- include "thanos-receive.ingestor.selectorLabels" . | nindent 4 }}
