apiVersion: route.openshift.io/v1
kind: Route 
metadata:
  labels:
    {{- include "thanos-receive.router.labels" . | nindent 4 }}
  name: {{ include "thanos-receive.name" . }}-router              
spec:  
  host:
  {{- if .Values.router.route.tlsEnabled }}
  tls:
    {{- toYaml .Values.router.route.tls | nindent 4 }}
  {{ end }}
  to:
    kind: Service
    name: {{ include "thanos-receive.name" . }}-router
    weight: 100
  wildcardPolicy: None