apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "thanos-receive.router.labels" . | nindent 4 }}
  name: {{ include "thanos-receive.name" . }}-router
spec:
  replicas: {{ .Values.router.replicaCount }}
  selector:
    matchLabels:
      {{- include "thanos-receive.router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thanos-receive.router.labels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - receive
            - --log.level=info
            - --log.format=logfmt
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --remote-write.address=0.0.0.0:19291
            - --http.config=/var/lib/thanos-http/config.yaml
            - --receive.replication-factor=1
            - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
            - --label=replica="$(NAME)"
            - --label=receive="true"
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: "{{ .Values.router.image.repository }}:{{ .Values.router.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.router.image.pullPolicy }}
          livenessProbe:
            {{- toYaml .Values.router.livenessProbe | nindent 12 }}
          name: thanos-receive
          ports:
            - containerPort: 10901
              name: grpc
            - containerPort: 10902
              name: http
            - containerPort: 19291
              name: remote-write
          readinessProbe:
            {{- toYaml .Values.router.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.router.resources | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /var/lib/thanos-receive
              name: hashring-config
            - mountPath:  /var/lib/thanos-http
              name: thanos-receive-auth  
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ include "thanos-receive.name" . }}-router
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: hashring-config
          name: hashring-config
        - name: thanos-receive-auth
          secret:  
            secretName: thanos-receive-auth  

