apiVersion: v1
data:
  hashrings.json: '[{"endpoints": ["{{ include "thanos-receive.name" . }}-ingestor-default-0.{{ include "thanos-receive.name" . }}-ingestor-default.{{ .Release.Namespace }}.svc.cluster.local:10901"], "hashring": "default", "tenants": [ ]}]'
kind: ConfigMap
metadata:
  name: hashring-config
