apiVersion: batch/v1
kind: Job
metadata:
  name: metrics-configure-remote-write
  namespace: openshift-user-workload-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers: 
        - image: quay.io/kuadrant/observability-configure:latest
          command: ["patch.sh"]
          name: "configure"
      restartPolicy: OnFailure 
  backoffLimit: 15   