apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: job-role
rules:
- apiGroups:
  - ""
  - "operator.authorino.kuadrant.io"
  - "route.openshift.io"
  - "rbac.authorization.k8s.io"
  - "monitoring.coreos.com"
  resources:
  - "routes"
  - "configmaps"
  - "services"
  - "endpoints"
  - "serviceaccounts"
  - "authorinos"
  - "serviceaccounts"
  - "serviceaccounts/token"
  - "secrets"
  - "servicemonitors"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: job-cluster-role
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: job-role-binding
  namespace: openshift-user-workload-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-user-workload-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: job-role-binding-openshift-user-workload-monitoring
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-user-workload-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  creationTimestamp: null
  name: job-role-binding-kuadrant-system
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kuadrant-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  creationTimestamp: null
  name: job-cluster-role-binding-kuadrant-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: kuadrant-system
