kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ingress-gateway.name" . }}-aws-credentials
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accesskey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
type: kuadrant.io/aws