apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "ingress-gateway.name" . }}
  labels:
    kuadrant.io/lb-attribute-geo-code: {{ .Values.gateway.geoCode }}
spec:
  gatewayClassName: {{ .Values.gateway.class }}
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: "{{ .Values.gateway.listeners.api.hostName }}"
      name: {{ .Values.gateway.name }}
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: {{ .Values.gateway.name }}-tls
        mode: Terminate

