replicaCount: 1

image:
  repository: quay.io/thanos/thanos
  pullPolicy: IfNotPresent
  tag: "v0.29.0"

livenessProbe:
  failureThreshold: 4
  httpGet:
    path: /-/healthy
    port: 9090
    scheme: HTTP
  periodSeconds: 30

readinessProbe:
  failureThreshold: 20
  httpGet:
    path: /-/ready
    port: 9090
    scheme: HTTP
  periodSeconds: 5

resources: {}

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect