kind: Istio
apiVersion: sailoperator.io/v1alpha1
metadata:
  name: {{ include "istio.name" . }}
spec:
  version: {{ .Values.istio.version }}
  namespace: {{ .Release.Namespace }}
  # Disable autoscaling to reduce dev resources
  values:
    pilot:
      autoscaleEnabled: false